# Generated by Django 5.2.7 on 2025-11-30 15:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_brand', models.CharField(max_length=100, unique=True)),
                ('tara_origine', models.CharField(blank=True, max_length=50)),
                ('an_infiintare', models.IntegerField(blank=True, null=True)),
                ('culoare', models.CharField(choices=[('#C0C0C0', 'Argintiu'), ('#FFD700', 'Auriu'), ('#000000', 'Negru'), ('#0000FF', 'Albastru')], default='#C0C0C0', max_length=50)),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='imagini_branduri/')),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('descriere', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_curea', models.CharField(max_length=100)),
                ('latime_curea', models.IntegerField()),
                ('culoare', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_mecanism', models.CharField(choices=[('AUT', 'Automatic'), ('MEC', 'Mecanic (Manual)'), ('QRT', 'Quartz'), ('SOL', 'Solar'), ('SPR', 'Spring Drive')], default='QRT', max_length=3)),
                ('frecventa', models.CharField(blank=True, max_length=50, null=True)),
                ('precizie', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_oferta', models.CharField(default='Promotie', max_length=100)),
                ('data_inceput', models.DateTimeField(auto_now_add=True)),
                ('data_sfarsit', models.DateTimeField()),
                ('cod_reducere', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefon', models.CharField(blank=True, max_length=15, null=True)),
                ('adresa', models.TextField(blank=True, max_length=300, null=True)),
                ('oras', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('data_nasterii', models.DateField(blank=True, null=True)),
                ('abonat_newsletter', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ceasuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_model', models.CharField(max_length=255)),
                ('stoc', models.IntegerField(default=0)),
                ('tip_geam', models.CharField(max_length=50)),
                ('diametru_carcasa', models.IntegerField(null=True)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('poza', models.ImageField(blank=True, null=True, upload_to='imagini_ceasuri/')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aplicatie.brand')),
                ('caracteristici', models.ManyToManyField(blank=True, to='aplicatie.caracteristici')),
                ('curea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aplicatie.curea')),
                ('mecanism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aplicatie.mecanism')),
                ('oferta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicatie.oferta')),
            ],
        ),
    ]
