# Generated by Django 5.2.7 on 2025-10-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_brand', models.CharField(max_length=100, unique=True)),
                ('tara_origine', models.CharField(blank=True, max_length=50)),
                ('an_infiintare', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('descriere', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ceasuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_model', models.CharField(max_length=255)),
                ('stoc', models.IntegerField(default=0)),
                ('tip_geam', models.CharField(max_length=50)),
                ('diametru_carcasa', models.IntegerField()),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Curea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_curea', models.CharField(max_length=100)),
                ('latime_curea', models.IntegerField()),
                ('culoare', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_mecanism', models.CharField(choices=[('AUT', 'Automatic'), ('MEC', 'Mecanic (Manual)'), ('QRT', 'Quartz'), ('SOL', 'Solar'), ('SPR', 'Spring Drive')], default='QRT', max_length=3)),
                ('frecventa', models.CharField(blank=True, max_length=50, null=True)),
                ('precizie', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_oferta', models.CharField(default='Promotie', max_length=100)),
                ('data_inceput', models.DateTimeField(auto_now_add=True)),
                ('data_sfarsit', models.DateTimeField()),
                ('cod_reducere', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Locatie',
        ),
        migrations.DeleteModel(
            name='Organizator',
        ),
    ]
