# Generated by Django 5.2.7 on 2025-11-04 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0002_brand_caracteristici_ceasuri_curea_mecanism_oferta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceasuri',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aplicatie.brand'),
        ),
        migrations.AddField(
            model_name='ceasuri',
            name='caracteristici',
            field=models.ManyToManyField(blank=True, null=True, to='aplicatie.caracteristici'),
        ),
        migrations.AddField(
            model_name='ceasuri',
            name='curea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aplicatie.curea'),
        ),
        migrations.AddField(
            model_name='ceasuri',
            name='mecanism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aplicatie.mecanism'),
        ),
        migrations.AddField(
            model_name='ceasuri',
            name='oferta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicatie.oferta'),
        ),
    ]
