# Generated by Django 5.2.7 on 2025-11-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0003_ceasuri_brand_ceasuri_caracteristici_ceasuri_curea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceasuri',
            name='caracteristici',
            field=models.ManyToManyField(blank=True, to='aplicatie.caracteristici'),
        ),
    ]
