# Generated by Django 5.2.7 on 2025-11-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0004_alter_ceasuri_caracteristici'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceasuri',
            name='culoare',
            field=models.CharField(choices=[('argintiu', 'Argintiu'), ('auriu', 'Auriu'), ('negru', 'Negru'), ('albastru', 'Albastru')], default='argintiu', max_length=50),
        ),
        migrations.AddField(
            model_name='ceasuri',
            name='imagine',
            field=models.ImageField(blank=True, null=True, upload_to='imagini_ceasuri/'),
        ),
        migrations.AlterField(
            model_name='ceasuri',
            name='diametru_carcasa',
            field=models.IntegerField(null=True),
        ),
    ]
