# Generated by Django 5.2.7 on 2025-11-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0005_ceasuri_culoare_ceasuri_imagine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceasuri',
            name='culoare',
        ),
        migrations.RemoveField(
            model_name='ceasuri',
            name='imagine',
        ),
        migrations.AddField(
            model_name='brand',
            name='culoare',
            field=models.CharField(choices=[('argintiu', 'Argintiu'), ('auriu', 'Auriu'), ('negru', 'Negru'), ('albastru', 'Albastru')], default='argintiu', max_length=50),
        ),
        migrations.AddField(
            model_name='brand',
            name='imagine',
            field=models.ImageField(blank=True, null=True, upload_to='imagini_ceasuri/'),
        ),
    ]
