# Generated by Django 5.2.7 on 2025-11-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0006_remove_ceasuri_culoare_remove_ceasuri_imagine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='imagine',
            field=models.ImageField(blank=True, null=True, upload_to='imagini_branduri/'),
        ),
    ]
