# Generated by Django 5.2.7 on 2025-11-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0007_alter_brand_imagine'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceasuri',
            name='poza',
            field=models.ImageField(blank=True, null=True, upload_to='imagini_ceasuri/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='culoare',
            field=models.CharField(choices=[('#C0C0C0', 'Argintiu'), ('#FFD700', 'Auriu'), ('#000000', 'Negru'), ('#0000FF', 'Albastru')], default='#C0C0C0', max_length=50),
        ),
    ]
